moodle/urls.py
from django.contrib import admin
from django.urls import include, path

from moodle.views import CursoView, ProvaView, QuestoesViews

app_name = 'moodle'

urlpatterns = [
    path('', CursoView.CursoListView.as_view(), name='home'),
    path('curso/<int:pk>/', CursoView.CursoDetailView.as_view(), name='curso-detail'),
    path('questoes/', QuestoesViews.QuestoesListView.as_view(), name='questoes'),
    path('provas/', ProvaView.ProvaListView.as_view(), name='provas'),
    path('provas/<int:prova_id>/', ProvaView.exibirProva, name='exibir-prova'),
    path('provas/<int:prova_id>/corrigir/',
         ProvaView.corrigirProva, name='corrigir-prova'),
     path('provas/<int:prova_id>/relatorio/',
         ProvaView.relatorioProva, name='relatorio-prova'),
    path('provas/<int:prova_id>/alunos/',
         ProvaView.alunos_provas_feitas, name='alunos-provas'),
    path('questoes/create/', QuestoesViews.QuestaoAlternativasCreateView.as_view(),
         name='questoes-create'),
    path('provas/create/', ProvaView.ProvaCreateView.as_view(), name='provas-create'),
    path('provas/finalizar/<int:prova_id>/',
         ProvaView.finalizarProva, name='finalizar-prova'),
    # path('questoes/update/<int:pk>/', QuestoesViews.QuestaoAlternativasUpdateView.as_view(), name='questoes-update'),
    path('provas/update/<int:pk>/',
         ProvaView.ProvaUpdateView.as_view(), name='provas-update'),
    path('questoes/delete/<int:pk>/',
         QuestoesViews.QuestoesDeleteView.as_view(), name='questoes-delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moodle.urls')),
    path('user/', include('user.urls'))

]

user/urls.py
from django.contrib import admin
from django.urls import include, path

from user import views

"""
@package user
Aqui estão definidas as Urls relacionadas ao login e logout de usuario.
"""

app_name = 'user'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout')

]

templates/partials/head.html
{% load static %}

{% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> {% endcomment %}
<link rel="stylesheet" href="{% static '/css/style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

templates/partials/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark mb-4">
  <div class="container">
    <h1 class="text-light">Moodle</h1>
      {% if user.is_authenticated %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="ml-5 collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'moodle:home' %}">Home</a>
          </li>
          {% if user.user_type == 'Professor' %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'moodle:questoes' %}">Questões</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'moodle:provas' %}">Provas</a>
          </li>
          {% endif %}
          <li class="nav-item ml-4">
            <form action="{% url 'user:logout' %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="email" value="{{request.user.email}}">

              <button class="plaintext-button mt-2 bg-dark text-light" type="submit"> Logout</button>
          </form>
          </li>
        </ul>
      </div>

      {% endif %}
  </div>
</nav>