moodle/urls.py
from django.contrib import admin
from django.urls import include, path

from moodle.views import CursoView, ProvaView, QuestoesViews

app_name = 'moodle'

urlpatterns = [
    path('', CursoView.CursoListView.as_view(), name='home'),
    path('curso/<int:pk>/', CursoView.CursoDetailView.as_view(), name='curso-detail'),
    path('questoes/', QuestoesViews.QuestoesListView.as_view(), name='questoes'),
    path('provas/', ProvaView.ProvaListView.as_view(), name='provas'),
    path('provas/<int:prova_id>/', ProvaView.exibirProva, name='exibir-prova'),
    path('provas/<int:prova_id>/corrigir/',
         ProvaView.corrigirProva, name='corrigir-prova'),
     path('provas/<int:prova_id>/relatorio/',
         ProvaView.relatorioProva, name='relatorio-prova'),
    path('provas/<int:prova_id>/alunos/',
         ProvaView.alunos_provas_feitas, name='alunos-provas'),
    path('questoes/create/', QuestoesViews.QuestaoAlternativasCreateView.as_view(),
         name='questoes-create'),
    path('provas/create/', ProvaView.ProvaCreateView.as_view(), name='provas-create'),
    path('provas/finalizar/<int:prova_id>/',
         ProvaView.finalizarProva, name='finalizar-prova'),
    # path('questoes/update/<int:pk>/', QuestoesViews.QuestaoAlternativasUpdateView.as_view(), name='questoes-update'),
    path('provas/update/<int:pk>/',
         ProvaView.ProvaUpdateView.as_view(), name='provas-update'),
    path('questoes/delete/<int:pk>/',
         QuestoesViews.QuestoesDeleteView.as_view(), name='questoes-delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moodle.urls')),
    path('user/', include('user.urls'))

]

user/urls.py
from django.contrib import admin
from django.urls import include, path

from user import views

"""
@package user
Aqui estão definidas as Urls relacionadas ao login e logout de usuario.
"""

app_name = 'user'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout')

]

moodle/models.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models

"""
@package moodle

@brief Aqui são definidos os models para relações do banco de dados.
"""


class Departamento(models.Model):
    """
    Define os atributos do elemento Departamento no banco de dados.
    @param models.Model
    """
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Professor(models.Model):
    """
    Define os atributos do elemento Professor no banco de dados.
    @param models.Model
    """
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.name


class Aluno(models.Model):
    """
    Define os atributos do elemento Aluno no banco de dados.
    @param models.Model
    """
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.user.name


class Disciplina(models.Model):
    """
    Define os atributos do elemento Disciplina no banco de dados.
    @param models.Model
    """
    nome = models.CharField(max_length=100)
    professor = models.ForeignKey(
        Professor, on_delete=models.SET_NULL, null=True)
    aluno = models.ManyToManyField(Aluno, through='Inscricao')
    quantidade_alunos = models.IntegerField(default=0)

    def __str__(self):
        return self.nome


class Inscricao(models.Model):
    """
    Define os atributos do elemento Inscrição no banco de dados.
    @param models.Model
    """
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE)
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)

    def __str__(self):
        return self.disciplina.nome + ' - ' + self.aluno.user.name


class Questao(models.Model):
    """
    Define os atributos do elemento Questão no banco de dados.
    @param models.Model
    """
    gabarito_choices = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E')
    )

    peso = models.IntegerField()
    gabarito = models.CharField(max_length=1, choices=gabarito_choices)
    enunciado = models.TextField()
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)

    def __str__(self):
        return self.enunciado


class Alternativa(models.Model):
    """
    Define os atributos do elemento Alternativa no banco de dados.
    @param models.Model
    """
    opcoes = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E')
    )

    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    texto_alternativa = models.CharField(max_length=255)
    alternativa = models.CharField(max_length=1, choices=opcoes)

    def __str__(self):
        return self.texto_alternativa


class Prova(models.Model):
    """
    Define os atributos do elemento Prova no banco de dados.
    @param models.Model
    """
    nota_total = models.IntegerField()
    disciplina = models.ForeignKey(
        Disciplina, null=True, on_delete=models.SET_NULL)
    questao = models.ManyToManyField(Questao)
    descricao = models.TextField(null=True, blank=True)
    finalizada = models.BooleanField(default=False)
    data = models.DateTimeField(default=datetime.datetime.now)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)

    def __str__(self):
        return self.descricao


class CadernoResposta(models.Model):
    """
    Define os atributos do elemento CadernoResposta no banco de dados.
    @param models.Model
    """
    resposta_choices = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E')
    )

    resposta_aluno = models.CharField(max_length=1, choices=resposta_choices)
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    acertou = models.BooleanField(default=False)
    desempenho = models.ForeignKey('Desempenho', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        gabarito = self.questao.gabarito
        if gabarito == self.resposta_aluno:
            self.acertou = True
        super().save(*args, **kwargs)


class Desempenho(models.Model):
    """
    Define os atributos do elemento Desempenho no banco de dados.
    @param models.Model
    """
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    prova = models.ForeignKey(Prova, on_delete=models.CASCADE)
    nota = models.IntegerField()
    prova_finalizada = models.BooleanField(default=False)
    data = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return 'Aluno: ' + self.aluno.user.name + ' Prova: ' + self.prova.descricao

moodle/views/CursoView.py
import datetime

from django.views import generic

from moodle import models
from util.LoginRequired import MyLoginRequired


class PseudoDesempenho:
  def __init__(self, nota, data):
    self.nota = nota
    self.data = data

class CursoListView(MyLoginRequired, generic.ListView):
  context_object_name = 'cursos'
  queryset = models.Disciplina.objects.all()
  template_name = 'moodle/home.html'

  def get_template_names(self):
    user = self.request.user
    if user.user_type == 'Professor':
      self.template_name = 'moodle/home_professor.html'
      return self.template_name

    return self.template_name



  def get_queryset(self):
    user = self.request.user
    if user.user_type == 'Professor':
      professor = user.professor
      queryset = self.queryset.filter(professor=professor)
      return queryset

    aluno = user.aluno
    queryset = self.queryset.filter(aluno=aluno)
    return queryset


class CursoDetailView(MyLoginRequired, generic.DetailView):
    model = models.Disciplina
    context_object_name = 'disciplina'
    template_name = 'moodle/curso/curso_detail.html'

    def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      provas = self.get_object(self.queryset).prova_set.filter(finalizada=False)
      provas_finalizadas = self.get_object(self.queryset).prova_set.filter(finalizada=True)
      aluno = self.request.user.aluno
      provas_diponiveis = []
      provas_feitas = []
      for prova in provas:
        desempenho = prova.desempenho_set.filter(aluno=aluno)
        if desempenho:
          provas_feitas.append((prova, desempenho[0], True))
        else:
          provas_diponiveis.append(prova)

      for prova in provas_finalizadas:
        desempenho = prova.desempenho_set.filter(aluno=aluno)
        if desempenho:
          provas_feitas.append((prova, desempenho[0], True))
        else:
          desempenho = PseudoDesempenho(0, prova.data)
          provas_feitas.append((prova, desempenho, False))

      context['provas_diponiveis'] = provas_diponiveis
      context['provas_feitas'] = provas_feitas
      context['aluno'] = aluno
      return context

moodle/views/ProvaView.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpRequest
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic

from moodle import models
from moodle.forms import ProvaForm
from util.LoginRequired import MyLoginRequired
from util.ProfessorRequired import ProfessorRequiredMixin


class PseudoDesempenho:
  def __init__(self, nota, data):
    self.nota = nota
    self.data = data

class ProvaListView(ProfessorRequiredMixin, generic.ListView):
  context_object_name = 'provas'
  queryset = models.Prova.objects.all()
  template_name = 'moodle/prova/lista-provas.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['provasabertas'] = self.get_queryset().filter(finalizada=False)
    context['provasfinalizadas'] = self.get_queryset().filter(finalizada=True)
    return context

  def get_queryset(self):
    queryset = self.queryset
    professor = self.request.user.professor
    queryset = queryset.filter(professor=professor)
    return queryset


class ProvaCreateView(MyLoginRequired, ProfessorRequiredMixin, generic.CreateView):
    model = models.Prova
    form_class = ProvaForm
    template_name = 'moodle/prova/create.html'
    success_url = reverse_lazy('moodle:provas')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['professor'] = self.request.user.professor
        return kwargs
      
    def form_valid(self, form):
      print("ESTOU AQUI NO FORM_VALID")
      prova = form.save(commit=False)
      questoes = [models.Questao.objects.get(pk=int(id)) for id in self.request.POST.getlist('questoes')]
      prova.nota_total = 0
      prova.professor=self.request.user.professor
      prova.save()
      
      for questao in questoes:
        prova.nota_total += questao.peso
      prova.questao.set(questoes)
      
      return super().form_valid(form)

class ProvaUpdateView(MyLoginRequired, ProfessorRequiredMixin, generic.UpdateView):
    model = models.Prova
    form_class = ProvaForm
    template_name = 'moodle/prova/update.html'
    success_url = reverse_lazy('moodle:provas')

    def get_form_kwargs(self):
      kwargs = super().get_form_kwargs()
      kwargs['professor'] = self.request.user.professor
      return kwargs
  

    def form_valid(self, form):
      prova = form.save(commit=False)
      prova.disciplina = form.cleaned_data['disciplina']
      prova.descricao = form.cleaned_data['descricao']
      questoes = form.cleaned_data['questoes']
      prova.save()
      
      prova.questao.set(questoes)
      
      prova.nota_total = 0
      for questao in questoes:
        prova.nota_total += questao.peso
      
      
      return super().form_valid(form)


@login_required(login_url='user:login')
def finalizarProva(req, prova_id):
  try:
    prova = models.Prova.objects.get(pk=prova_id)
    prova.finalizada = True
    prova.data = datetime.datetime.now()
    prova.save()
  except ObjectDoesNotExist:
    raise Http404('Objects not found in database')

  return redirect('moodle:provas')

@login_required(login_url='user:login')
def exibirProva(req, prova_id):
  prova = models.Prova.objects.get(pk=prova_id)
  questoes = prova.questao.all()


  return render(req, 'moodle/prova/fazer_prova.html', {
    'questoes': questoes,
    'prova': prova,
  })
@login_required(login_url='user:login')
def corrigirProva(req: HttpRequest, prova_id):
  prova = models.Prova.objects.get(pk=prova_id)
  dados = req.POST
  questoes_resolvidas = []
  pk = prova.disciplina.id
  desempenho_aluno = models.Desempenho.objects.create(
    aluno = req.user.aluno,
    prova=prova,
    nota=0,
    prova_finalizada=True
  )
  for q in dados.keys():
    if 'quest' in q:
      questoes_resolvidas.append(dados.get(q))

  for i, questao in enumerate(prova.questao.all()):
    correto = False
    if questoes_resolvidas[i] == questao.gabarito:
      correto = True

    caderno_resposta = models.CadernoResposta.objects.create(
      resposta_aluno=questoes_resolvidas[i],
      acertou=correto,
      desempenho=desempenho_aluno,
      questao=questao
    )

    if correto:
      desempenho_aluno.nota += questao.peso
      desempenho_aluno.save()


  return redirect(reverse('moodle:curso-detail', args=(pk,)), context={'desempenho': desempenho_aluno})

def alunos_provas_feitas(req, prova_id):
  prova = models.Prova.objects.get(pk=prova_id)
  alunos = prova.disciplina.aluno.all()
  prova_finalizada = []
  for aluno in alunos:
    desempenho = prova.desempenho_set.filter(aluno=aluno)
    if desempenho:
      prova_finalizada.append((aluno, desempenho.first(), True))
    else:
      desempenho = PseudoDesempenho(0, prova.data)
      prova_finalizada.append((aluno, desempenho, False))

  print(prova_finalizada)
  return render(req, 'moodle/prova/alunos_provas.html', {
    'prova_finalizada': prova_finalizada,
    'prova': prova,
  })

def relatorioProva(req, prova_id):
  prova = models.Prova.objects.get(pk=prova_id)
  aluno = req.user.aluno
  desempenho = prova.desempenho_set.filter(aluno=aluno)
  respostas_aluno = desempenho[0].cadernoresposta_set.all()
  relatorio = []
  for resp in respostas_aluno:
    relatorio.append((resp.questao, resp.questao.peso, resp.questao.gabarito, resp.resposta_aluno))

  return render(req, 'moodle/curso/relatorio_prova.html', {
    'relatorio': relatorio,
  })

moodle/views/QuestoesViews.py
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View, generic
from django.views.generic.edit import FormMixin

from moodle import models
from moodle.forms import QuestaoAlternativasForm
from util.LoginRequired import MyLoginRequired
from util.ProfessorRequired import ProfessorRequiredMixin


class QuestoesListView(MyLoginRequired, ProfessorRequiredMixin, generic.ListView):
  context_object_name = 'questoes'
  #FILTRAR PELO DEPARTAMENTO DO PROFESSOR
  queryset = models.Questao.objects.all()
  template_name = 'moodle/questoes/lista-questoes.html'

  def get_queryset(self):
      queryset = self.queryset
      current_user = self.request.user
      if current_user.user_type == 'Professor':
        professor = current_user.professor
        queryset = queryset.filter(departamento=professor.departamento)
        return queryset

      return queryset


class QuestaoAlternativasCreateView(MyLoginRequired, ProfessorRequiredMixin, View):
  def get(self, request, *args, **kwargs):
    form = QuestaoAlternativasForm()
    return render(request, 'moodle/questoes/create.html', {'form': form})

  def post(self, request, *args, **kwargs):
    form = QuestaoAlternativasForm(data=request.POST)
    professor = self.request.user.professor

    if form.is_valid():
      # Salvar dados da questão
      questao = models.Questao.objects.create(
        enunciado=form.cleaned_data['enunciado'],
        peso=form.cleaned_data['peso'],
        gabarito=form.cleaned_data['gabarito'],
        departamento=professor.departamento,
        professor=professor
      )


      # Salvar dados das alternativas
      alternativa_a = models.Alternativa.objects.create(
        questao=questao,
        texto_alternativa=form.cleaned_data['alternativa_A'],
        alternativa='A'
      )

      alternativa_b = models.Alternativa.objects.create(
        questao=questao,
        texto_alternativa=form.cleaned_data['alternativa_B'],
        alternativa='B'
      )

      alternativa_c = models.Alternativa.objects.create(
        questao=questao,
        texto_alternativa=form.cleaned_data['alternativa_C'],
        alternativa='C'
      )

      alternativa_d = models.Alternativa.objects.create(
        questao=questao,
        texto_alternativa=form.cleaned_data['alternativa_D'],
        alternativa='D'
      )
      alternativa_e = models.Alternativa.objects.create(
        questao=questao,
        texto_alternativa=form.cleaned_data['alternativa_E'],
        alternativa='E'
      )

      return redirect('moodle:questoes')

    return render(request, 'moodle/questoes/create.html', {'form': form})

class QuestoesDeleteView(generic.DeleteView):
  model = models.Questao
  template_name = 'moodle/questoes/delete.html'
  success_url = reverse_lazy('moodle:questoes')

templates/moodle/prova/alunos_provas.html
{% extends 'moodle/global.html' %}
{% block content %}

  {% comment %} <h1 class="mb-3">CURSO: <span class="text-info">{{disciplina.nome}}</span></h1>
  <div class="container bg-light">
    <div class="d-flex justify-content-between">
      <h3 class="mb-3 mr-3">Professor: <span class="text-info">{{disciplina.professor}}</span></h3>
      <h3 class="mb-3">Aluno: <span class="text-info">{{aluno}}</span></h3>
    </div>
    <div class="container ml-4">
      <h5 class="mt-4">Provas disponíveis para serem feitas:</h5> {% endcomment %}

    <h5 class="mt-5">Alunos:</h5>
    <br>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Aluno</th>
            <th scope="col">Nota Máxima</th>
            <th scope="col">Resultado</th>
            <th scope="col">Feitas</th>
            <th scope="col">Data</th>
          </tr>
        </thead>
        <tbody>
        {% for aluno, desempenho, feita in prova_finalizada %}
          <tr>
            <td>{{aluno.user.name}}</td>
            <td>{{prova.nota_total}}</td>
            <td>{{desempenho.nota}}</td>
            <td>
              {% if feita %}
              &#x2705
              {% else %}
              &#x274C
              {% endif %}
            </td>
            <td>{{desempenho.data}}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table


{% endblock %}

templates/moodle/prova/create.html
{% extends 'moodle/global.html' %}
{% block content %}

<h1>CRIAR PROVA</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Prova</button>
</form>

{% endblock content %}

templates/moodle/prova/fazer_prova.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>PROVA</h1>
  <div>
    <h2>Descrição: {{prova.descricao}}</h2>
    <h3>Nota: {{prova.nota_total}}</h3>
  </div>
  <form action="{% url 'moodle:corrigir-prova' prova.id%}" method="post">
    {% csrf_token %}
    {% for questao in questoes %}
      <fieldset>
        <legend>Questão {{ forloop.counter }}: {{ questao }}</legend>
        <p>{{questao.enunciado}}</p>
        {% for op in questao.alternativa_set.all %}
          <input type="radio" name="question{{ questao.id }}" value="{{op.alternativa}}" required>
          <label for="{{op.alternativa}}{{ questao.id }}">{{op.alternativa}}) {{op.texto_alternativa}}</label>
        {% endfor %}
      </fieldset>

    {% endfor %}
    <button type="submit">Confirmar</button>
  </form>
</body>
</html>

templates/moodle/prova/lista-provas.html
{% extends 'moodle/global.html' %}
{% block content %}
  <h1 class="text-info mb-4">{{user.name}} essas são suas provas:</h1>
  <h2 class="mb-5">Para montar a sua prova<a href="{% url 'moodle:provas-create' %}"> Clique aqui.</a></h2>
  {% if provasabertas %}
    <div class="container text-center bg-dark mb-5">
      <h3 class="text-light p-3">Provas que estão disponíveis:</h3>
      {% for prova in provasabertas %}

      <div class="row bg-light">
        <div class="col-sm-8 mb-3">
          <div class="d-flex justify-content-between">
            <h5 class="text-dark text-md mt-3 ml-3" >Descrição: {{prova.descricao}}</h5>
            <h5 class="text-dark text-md mt-3" >Disciplina: {{prova.disciplina}}</h5>
          </div>

          <p>
            <button class="btn btn-primary mt-4" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
              Questões da prova
            </button>
          </p>
          <div class="collapse" id="collapseExample">
            <div class="card card-body">
              {% for questao in prova.questao.all %}
              <div class="row bg-light">
                <div class="col-sm-8">
                  <p>{{ forloop.counter }}) {{questao.enunciado}}</p>

                </div>

                <div class="col-sm-2">
                  Valor: {{questao.peso}}
                </div>
                <div class="col-sm-2">
                  Gabarito: {{questao.gabarito}}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>

        </div>
        <div class="col-sm-4 mb-auto">
          <p class="text-info mt-3">Valor da prova: {{prova.nota_total}}</p>
          <a class="btn btn-primary mb-3 mt-2"href="{% url 'moodle:provas-update' prova.id %}" role="button">Editar prova</a>
          <a class="btn btn-primary mb-3 mt-2"href="{% url 'moodle:finalizar-prova' prova.id %}" role="button">Finalizar prova</a>

        </div>
      </div>
      <span class="text-dark">a</span>
      {% endfor %}

    </div>
  {% endif %}


  {% if provasfinalizadas %}
    <div class="container text-center bg-secondary mb-5">
      <h3 class="text-light p-3">Provas que foram finalizadas</h3>
      {% for prova in provasfinalizadas %}

      <div class="row bg-light">
        <div class="col-sm-8 mb-3">
          <div class="d-flex justify-content-between">
            <h5 class="text-dark text-md mt-3 ml-3" >Descrição: {{prova.descricao}}</h5>
            <h5 class="text-dark text-md mt-3" >Disciplina: {{prova.disciplina}}</h5>
          </div>
          <p>
            <button class="btn btn-primary mt-4" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
              Questões da prova
            </button>
          </p>
          <div class="collapse" id="collapseExample">
            <div class="card card-body">
              {% for questao in prova.questao.all %}
              <div class="row bg-light">
                <div class="col-sm-8">
                  <p>{{questao.enunciado}}</p>

                </div>

                <div class="col-sm-2">
                  Valor: {{questao.peso}}
                </div>
                <div class="col-sm-2">
                  Gabarito: {{questao.gabarito}}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>

        </div>
        <div class="col-sm-4 mb-auto">
          <p class="text-info mt-5">Valor da prova: {{prova.nota_total}}</p>
          <p class="text-info mt-3">Data de finalização: {{prova.data}}</p>
          <p class="text-info mt-3"><a href="{% url 'moodle:alunos-provas' prova.id %}">Alunos que fizeram</a></p>
        </div>
      </div>
      <span class="text-secondary">a</span>
      {% endfor %}

    </div>
  {% endif %}
{% endblock content %}

templates/moodle/prova/update.html
{% extends 'moodle/global.html' %}
{% block content %}

<h1>ATUALIZAR PROVA</h1>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group">
      <label for="{{ field.auto_id }}">{{ field.label }}</label>
      {{ field }}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Criar</button>
</form>

{% endblock content %}